// mcgradient-svelte/src/App.svelte
<script lang="ts">
  import { blocks, getBlockByName, type Block } from "./lib/blocks";

  let currentBlock: Block = getBlockByName("granite");

  let searchedBlockName = "";
  function setCurrentBlockName(name: string) {
    currentBlock = getBlockByName(name);
    searchedBlockName = "";

    updateSimiliar();
  }

  let maxHDiff = "0.1";
  let maxSDiff = "0.1";
  let maxLDiff = "0.2";

  let similiarBlocks: Block[] = [];

  function updateSimiliar() {
    similiarBlocks = blocks.filter((b) => {
      if (b.name === currentBlock.name) return false;

      const hDiff = Math.abs(b.color.hue - currentBlock.color.hue);
      const sDiff = Math.abs(
        b.color.saturation - currentBlock.color.saturation
      );
      const lDiff = Math.abs(b.color.lightness - currentBlock.color.lightness);

      return (
        hDiff < Number(maxHDiff) &&
        sDiff < Number(maxSDiff) &&
        lDiff < Number(maxLDiff)
      );
    });
  }

  // TODO:
  function compareBlocks(a: Block, b: Block) {
    return a.color.saturation - b.color.saturation;
  }

  let hoveringOverBlock: Block | null = null;
  function setHoveringOverBlock(block: Block) {
    hoveringOverBlock = block;
  }

  setCurrentBlockName("granite");
</script>

<div class="h-screen flex flex-col justify-start p-8 gap-8 relative">
  <input
    class="w-full px-2 py-4"
    bind:value={searchedBlockName}
    placeholder="Search block..."
  />

  {#if currentBlock != null}
    <div class="flex-shrink-0 flex justify-center items-center gap-4">
      <!-- svelte-ignore a11y-no-static-element-interactions -->
      <!-- svelte-ignore a11y-click-events-have-key-events -->
      <div
        class="w-20 aspect-square object-contain flex-shrink-0 flex-grow-0"
        on:mouseenter={() => setHoveringOverBlock(currentBlock)}
      >
        <img
          class={`pixel-image w-full h-full`}
          src={"block/" + currentBlock.fileName}
          alt=""
        />
      </div>

      <div class="flex flex-col justify-center items-center">
        <div class="flex justify-between gap-4">
          Hue difference
          <div>
            {maxHDiff}
          </div>
          <input
            type="range"
            min="0"
            max="1"
            step="0.001"
            bind:value={maxHDiff}
            on:input={() => updateSimiliar()}
          />
        </div>
        <div class="flex justify-between gap-4">
          <div>
            {maxSDiff}
          </div>
          Saturation difference
          <input
            type="range"
            min="0"
            max="1"
            step="0.001"
            bind:value={maxSDiff}
            on:input={() => updateSimiliar()}
          />
        </div>
        <div class="flex justify-between gap-4">
          Lightness difference
          <div>
            {maxLDiff}
          </div>
          <input
            type="range"
            min="0"
            max="1"
            step="0.001"
            bind:value={maxLDiff}
            on:input={() => updateSimiliar()}
          />
        </div>
      </div>
    </div>

    <div class="w-full gap-2 overflow-scroll flex flex-wrap justify-center">
      {#each similiarBlocks.sort(compareBlocks) as block}
        <!-- svelte-ignore a11y-no-static-element-interactions -->
        <!-- svelte-ignore a11y-click-events-have-key-events -->
        <div
          class="w-20 aspect-square object-contain flex-shrink-0 flex-grow-0"
          on:mouseenter={() => setHoveringOverBlock(block)}
          on:click={() => setCurrentBlockName(block.name)}
        >
          <img
            class={`pixel-image w-full h-full`}
            src={"block/" + block.fileName}
            alt=""
          />
        </div>
      {/each}
    </div>
  {/if}

  <!-- Search -->
  {#if searchedBlockName.length > 0}
    <div
      class="absolute top-24 right-8 left-8 bottom-8 gap-4 flex flex-col bg-white"
    >
      <div class="w-full gap-2 overflow-scroll flex flex-wrap justify-center">
        {#each blocks.filter( (b) => b.name.includes(searchedBlockName) ) as block}
          <!-- svelte-ignore a11y-no-static-element-interactions -->
          <!-- svelte-ignore a11y-click-events-have-key-events -->
          <div
            class="w-20 aspect-square object-contain flex-shrink-0 flex-grow-0"
            on:mouseenter={() => setHoveringOverBlock(block)}
            on:click={() => setCurrentBlockName(block.name)}
          >
            <img
              class={`pixel-image w-full h-full`}
              src={"block/" + block.fileName}
              alt=""
            />
          </div>
        {/each}
      </div>
    </div>
  {/if}

  {#if hoveringOverBlock != null}
    <div class="absolute top-0 left-0 bg-[rgba(0,0,0,0.5)] text-white">
      {hoveringOverBlock.name} (H: {hoveringOverBlock.color.hue}, S: {hoveringOverBlock
        .color.saturation}, L: {hoveringOverBlock.color.lightness})
    </div>
  {/if}
</div>

<style>
  .pixel-image {
    image-rendering: pixelated;
    image-rendering: -moz-crisp-edges;
    image-rendering: crisp-edges;
  }
</style>

// src/App.tsx
import { useEffect, useState } from "react";
import {
  Block,
  allBlocks,
  getBlockByName,
  getSimiliarBlocks,
} from "./lib/blocks";

function App() {
  const [selectedBlock, setSelectedBlock] = useState<Block | null>(null);
  const [maxColorDistance, setMaxColorDistance] = useState<number>(6);
  const [similiarBlocks, setSimiliarBlocks] = useState<Block[]>([]);

  const [searchedBlockName, setSearchedBlockName] = useState<string>("");
  const [isSearching, setIsSearching] = useState<boolean>(false);

  const [hoveringOverBlock, setHoveringOverBlock] = useState<Block | null>(
    null
  );

  useEffect(() => {
    setSelectedBlock(getBlockByName("stone"));
  }, []);

  useEffect(() => {
    setIsSearching(false);
  }, [selectedBlock]);

  useEffect(() => {
    if (!selectedBlock) return;
    setSearchedBlockName("");

    setSimiliarBlocks(getSimiliarBlocks(selectedBlock, maxColorDistance));
  }, [selectedBlock, maxColorDistance]);

  function showSearchResults() {
    const matchingBlocks = allBlocks.filter((b) => {
      const nameParts = b.name.toLowerCase().split("_");

      for (const namePart of nameParts) {
        if (namePart.startsWith(searchedBlockName.toLowerCase())) return true;
      }

      return false;
    });

    if (matchingBlocks.length === 0)
      return <div className="font-semibold text-xl">No blocks found</div>;

    return matchingBlocks.map((b) => (
      <div
        key={b.fileName}
        className="w-20 aspect-square object-contain flex-shrink-0 flex-grow-0"
        onMouseEnter={() => setHoveringOverBlock(b)}
        onClick={() => setSelectedBlock(b)}
      >
        <img
          className={`pixelated w-full h-full`}
          src={"block/" + b.fileName}
          alt=""
        />
      </div>
    ));
  }

  return (
    <div className="h-screen flex-col flex">
      {/* Header */}
      <div className="border-b border-slate-300 flex bg-white p-4 shadow-sm justify-between bg-gradient-to-r">
        <input
          value={searchedBlockName}
          onChange={(e) => {
            setSearchedBlockName(e.target.value);
          }}
          className="px-2 py-2"
          placeholder="Search block..."
          onFocus={() => setIsSearching(true)}
        />
      </div>

      {/* Selected block */}
      {selectedBlock && (
        <div className="flex-shrink-0 flex justify-center items-center gap-4 my-4">
          <div
            className="w-20 aspect-square object-contain flex-shrink-0 flex-grow-0"
            // on:mouseenter={() => setHoveringOverBlock(currentBlock)}
          >
            <img
              className={`pixelated w-full h-full`}
              src={"block/" + selectedBlock.fileName}
              alt=""
            />
          </div>

          <div className="flex flex-col justify-center items-center">
            <div className="flex justify-between gap-4">
              Similiarity
              <div>{maxColorDistance}</div>
              <input
                type="range"
                min="0"
                max="100"
                step="0.1"
                value={maxColorDistance}
                onChange={(e) => setMaxColorDistance(Number(e.target.value))}
              />
            </div>
          </div>
        </div>
      )}

      {/* Similiar blocks */}
      <div className="overflow-scroll rounded-md bg-white p-4 shadow-sm m-4 border-slate-300 flex-grow flex flex-col">
        <div className="flex flex-wrap justify-center gap-2">
          {similiarBlocks.map((similiarBlock) => (
            <div
              key={similiarBlock.fileName}
              className="w-20 aspect-square object-contain flex-shrink-0 flex-grow-0"
              onMouseEnter={() => setHoveringOverBlock(similiarBlock)}
              onClick={() => setSelectedBlock(similiarBlock)}
            >
              <img
                className={`pixelated w-full h-full`}
                src={"block/" + similiarBlock.fileName}
                alt=""
              />
            </div>
          ))}
        </div>
      </div>

      {/* Search */}
      {isSearching && (
        <div className="absolute top-20 left-0 right-0 bottom-0 p-4 pt-0 bg-white flex flex-col">
          <div className="p-4 flex justify-between items-center flex-shrink-0">
            <div className="text-slate-400 text-xl">Search results</div>
            <div className="text-slate-400 text-xl">X</div>
          </div>

          <div className="overflow-y-scroll h-full">
            <div className="flex flex-wrap justify-center gap-2">
              {showSearchResults()}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default App;
